### ISSUE TITLE
0.54 版本shell 版本太低了。有很多 bug

### ISSUE THREAD

**Issue by zhuliminl** [bozaigao/Taro-demo-rn-shell#1]
建议搞一个高一点版本的。还可以多平台写 hooks，现在要想兼容 rn，都写不了 hooks

**Comment by bozaigao** [comment]
有时间会基于Taro升级一下rn版本，目前taro官方用的版本就是0.55.4,升级的话会改很多东西，所以官方也一直都还没升级
