### ISSUE TITLE
你好，用这个壳子如何打包呢？

### ISSUE THREAD

**Issue by place222** [bozaigao/Taro-demo-rn-shell#2]

**Comment by bozaigao** [comment]
直接将Taro-demo生成的dist rn目录下的文件拷贝到Taro-demo-shell src里面覆盖然后在项目根目录执行rn打包命令即可,iOS打包命令：react-native bundle --platform ios --entry-file index.js --bundle-output ./ios/main.jsbundle --assets-dest ./ios --dev false
Android打包命令:react-native bundle --entry-file index.js --platform android --dev false --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res/
不过现在基本不用手动打包了，android用AS生成release包会自动执行打包脚本，iOS也一样
